<?php

namespace Core\LuckyBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * WclassRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WclassRepository extends EntityRepository
{
}
